sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t milo/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true milo/docker-react-app npm run test -- --coverage
after_success:
  - echo "Test Success"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-879757627605
  bucket-path: docker-react-app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
